import numpy as np
import matplotlib.pyplot as plt
import matplotlib

#Filter
Critic_1_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_1_Lay1_history')
Critic_1_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_1_Lay2_history')
Critic_2_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_2_Lay1_history')
Critic_2_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_2_Lay2_history')
Actor_1_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_1_Lay1_history')
Actor_1_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_1_Lay2_history')
Actor_2_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_2_Lay1_history')
Actor_2_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_2_Lay2_history')

#TS
Critic_1_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_1_Lay1_history')
Critic_1_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_1_Lay2_history')
Critic_2_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_2_Lay1_history')
Critic_2_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_2_Lay2_history')
Actor_1_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_1_Lay1_history')
Actor_1_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_1_Lay2_history')
Actor_2_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_2_Lay1_history')
Actor_2_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_2_Lay2_history')


#Vanilla
Critic_1_Lay1_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Critic_1_Lay1_history')
Critic_1_Lay2_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Critic_1_Lay2_history')
Critic_2_Lay1_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Critic_2_Lay1_history')
Critic_2_Lay2_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Critic_2_Lay2_history')
Actor_1_Lay1_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Actor_1_Lay1_history')
Actor_1_Lay2_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Actor_1_Lay2_history')
Actor_2_Lay1_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Actor_2_Lay1_history')
Actor_2_Lay2_history_vanilla = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/nosmooth_nofilter2/Actor_2_Lay2_history')




#filter
Critic_1_Lay1_history_reshape_filter = Critic_1_Lay1_history_filter[:40000,:]
Critic_1_Lay2_history_reshape_filter = Critic_1_Lay2_history_filter[:40000,:]
Critic_2_Lay1_history_reshape_filter = Critic_2_Lay1_history_filter[:40000,:]
Critic_2_Lay2_history_reshape_filter = Critic_2_Lay1_history_filter[:40000,:]
Actor_1_Lay1_history_reshape_filter = Actor_1_Lay1_history_filter[:40000,:]
Actor_1_Lay2_history_reshape_filter = Actor_1_Lay2_history_filter[:40000,:]
Actor_2_Lay1_history_reshape_filter = Actor_2_Lay1_history_filter[:40000,:]
Actor_2_Lay2_history_reshape_filter = Actor_2_Lay1_history_filter[:40000,:]

#TS
Critic_1_Lay1_history_reshape_TS = Critic_1_Lay1_history_TS[:40000,:]
Critic_1_Lay2_history_reshape_TS = Critic_1_Lay2_history_TS[:40000,:]
Critic_2_Lay1_history_reshape_TS = Critic_2_Lay1_history_TS[:40000,:]
Critic_2_Lay2_history_reshape_TS = Critic_2_Lay1_history_TS[:40000,:]
Actor_1_Lay1_history_reshape_TS = Actor_1_Lay1_history_TS[:40000,:]
Actor_1_Lay2_history_reshape_TS = Actor_1_Lay2_history_TS[:40000,:]
Actor_2_Lay1_history_reshape_TS = Actor_2_Lay1_history_TS[:40000,:]
Actor_2_Lay2_history_reshape_TS = Actor_2_Lay1_history_TS[:40000,:]

#vanilla
Critic_1_Lay1_history_reshape_vanilla = Critic_1_Lay1_history_vanilla[:40000,:]
Critic_1_Lay2_history_reshape_vanilla = Critic_1_Lay2_history_vanilla[:40000,:]
Critic_2_Lay1_history_reshape_vanilla = Critic_2_Lay1_history_vanilla[:40000,:]
Critic_2_Lay2_history_reshape_vanilla = Critic_2_Lay1_history_vanilla[:40000,:]
Actor_1_Lay1_history_reshape_vanilla = Actor_1_Lay1_history_vanilla[:40000,:]
Actor_1_Lay2_history_reshape_vanilla = Actor_1_Lay2_history_vanilla[:40000,:]
Actor_2_Lay1_history_reshape_vanilla = Actor_2_Lay1_history_vanilla[:40000,:]
Actor_2_Lay2_history_reshape_vanilla = Actor_2_Lay1_history_vanilla[:40000,:]


fig1 = plt.figure(figsize=(14,10))
plt.subplot(4,2,1)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,6],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,7],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,8],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,9],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,10],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,11],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,12],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,13],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,6],linewidth=1.0)
plt.grid(True)
plt.title('TS',fontsize=14)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\psi_{1}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,2)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,6],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,7],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,8],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,9],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,10],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,11],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,12],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,13],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,6],linewidth=1.0)
plt.grid(True)
plt.title('TS + Filter',fontsize=14)
plt.ylabel(r'$\psi_{1}$',fontsize=14)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,3)
plt.plot(Actor_1_Lay1_history_reshape_TS[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\vartheta_{1}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,4)
plt.plot(Actor_1_Lay1_history_reshape_filter[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\vartheta_{1}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,5)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,6],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,7],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,8],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,9],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,10],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,11],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,12],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,13],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,6],linewidth=1.0)
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\psi_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,6)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,6],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,7],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,8],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,9],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,10],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,11],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,12],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,13],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,6],linewidth=1.0)
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\psi_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,7)
plt.plot(Actor_2_Lay1_history_reshape_TS[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.xlabel('Time [s]',fontsize=14)
plt.ylabel(r'$\vartheta_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,8)
plt.plot(Actor_2_Lay1_history_reshape_filter[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.xlabel('Time [s]',fontsize=14)
plt.ylabel(r'$\vartheta_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.tight_layout()
plt.savefig('Network_comparison_filter.pdf',bbox_inches='tight', pad_inches=0.0, dpi=300)
plt.savefig('Network_comparison_filter.eps',bbox_inches='tight', pad_inches=0.0, dpi=300)

plt.show()

plt.show()