import numpy as np
import matplotlib.pyplot as plt
import matplotlib

#Filter
Critic_1_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_1_Lay1_history')
Critic_1_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_1_Lay2_history')
Critic_2_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_2_Lay1_history')
Critic_2_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Critic_2_Lay2_history')
Actor_1_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_1_Lay1_history')
Actor_1_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_1_Lay2_history')
Actor_2_Lay1_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_2_Lay1_history')
Actor_2_Lay2_history_filter = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/filter2/Actor_2_Lay2_history')

#TS
Critic_1_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_1_Lay1_history')
Critic_1_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_1_Lay2_history')
Critic_2_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_2_Lay1_history')
Critic_2_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Critic_2_Lay2_history')
Actor_1_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_1_Lay1_history')
Actor_1_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_1_Lay2_history')
Actor_2_Lay1_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_2_Lay1_history')
Actor_2_Lay2_history_TS = np.loadtxt('/home/yifei/PycharmProjects/SafeIHDP_controlloss18_smallgain_Vx/origion2/Actor_2_Lay2_history')



#filter
Critic_1_Lay1_history_reshape_filter = Critic_1_Lay1_history_filter[:40000,:]
Critic_1_Lay2_history_reshape_filter = Critic_1_Lay2_history_filter[:40000,:]
Critic_2_Lay1_history_reshape_filter = Critic_2_Lay1_history_filter[:40000,:]
Critic_2_Lay2_history_reshape_filter = Critic_2_Lay1_history_filter[:40000,:]
Actor_1_Lay1_history_reshape_filter = Actor_1_Lay1_history_filter[:40000,:]
Actor_1_Lay2_history_reshape_filter = Actor_1_Lay2_history_filter[:40000,:]
Actor_2_Lay1_history_reshape_filter = Actor_2_Lay1_history_filter[:40000,:]
Actor_2_Lay2_history_reshape_filter = Actor_2_Lay1_history_filter[:40000,:]

#TS
Critic_1_Lay1_history_reshape_TS = Critic_1_Lay1_history_TS[:40000,:]
Critic_1_Lay2_history_reshape_TS = Critic_1_Lay2_history_TS[:40000,:]
Critic_2_Lay1_history_reshape_TS = Critic_2_Lay1_history_TS[:40000,:]
Critic_2_Lay2_history_reshape_TS = Critic_2_Lay1_history_TS[:40000,:]
Actor_1_Lay1_history_reshape_TS = Actor_1_Lay1_history_TS[:40000,:]
Actor_1_Lay2_history_reshape_TS = Actor_1_Lay2_history_TS[:40000,:]
Actor_2_Lay1_history_reshape_TS = Actor_2_Lay1_history_TS[:40000,:]
Actor_2_Lay2_history_reshape_TS = Actor_2_Lay1_history_TS[:40000,:]


fig16 = plt.figure(figsize=(14,10))
plt.subplot(4,2,1)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,6],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,7],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,8],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,9],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,10],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,11],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,12],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_TS[:,13],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_TS[:,6],linewidth=1.0)
plt.grid(True)
plt.title('TS',fontsize=14)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\psi_{1}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,2)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,6],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,7],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,8],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,9],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,10],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,11],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,12],linewidth=1.0)
plt.plot(Critic_1_Lay1_history_reshape_filter[:,13],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_1_Lay2_history_reshape_filter[:,6],linewidth=1.0)
plt.grid(True)
plt.title('TS + Filter',fontsize=14)
plt.ylabel(r'$\psi_{1}$',fontsize=14)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,3)
plt.plot(Actor_1_Lay1_history_reshape_TS[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_TS[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\vartheta_{1}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,4)
plt.plot(Actor_1_Lay1_history_reshape_filter[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape_filter[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\vartheta_{1}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,5)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,6],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,7],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,8],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,9],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,10],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,11],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,12],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_TS[:,13],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_TS[:,6],linewidth=1.0)
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\psi_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,6)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,6],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,7],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,8],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,9],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,10],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,11],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,12],linewidth=1.0)
plt.plot(Critic_2_Lay1_history_reshape_filter[:,13],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,0],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,1],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,2],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,3],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,4],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,5],linewidth=1.0)
plt.plot(Critic_2_Lay2_history_reshape_filter[:,6],linewidth=1.0)
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.ylabel(r'$\psi_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,7)
plt.plot(Actor_2_Lay1_history_reshape_TS[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_TS[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_TS[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.xlabel('Time [s]',fontsize=14)
plt.ylabel(r'$\vartheta_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.subplot(4,2,8)
plt.plot(Actor_2_Lay1_history_reshape_filter[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_2_Lay1_history_reshape_filter[:,20],linewidth=1.0,color = 'C2')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape_filter[:,6],linewidth=1.0,color = 'C0')
plt.grid(True)
plt.xticks([0, 10000, 20000, 30000, 40000], ['0', '10', '20', '30', '40'],fontsize=14)
plt.xlabel('Time [s]',fontsize=14)
plt.ylabel(r'$\vartheta_{2}$',fontsize=14)
plt.yticks(fontsize=14)

plt.tight_layout()
plt.savefig('Network_comparison_filter.pdf',bbox_inches='tight', pad_inches=0.0, dpi=300)
plt.savefig('Network_comparison_filter.eps',bbox_inches='tight', pad_inches=0.0, dpi=300)

plt.show()

#Critic
fig1 = plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Critic_1_Lay1_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,6],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,7],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,8],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,10],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,11],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,12],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay1_history_reshape[:,13],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,6],linewidth=1.0,color = 'C0')
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Critic_1_Lay1_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Critic_1_Lay1_history')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

fig5 = plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Critic_1_Lay2_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Critic_1_Lay2_history_reshape[:,6],linewidth=1.0,color = 'C0')
#plt.plot(Critic_1_Lay2_history_reshape[:,7],linewidth=1.0,color = 'C0')
#plt.plot(Critic_1_Lay2_history_reshape[:,8],linewidth=1.0,color = 'C0')
#plt.plot(Critic_1_Lay2_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Critic_1_Lay2_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Critic_1_Lay1_Weights')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

fig6 = plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Critic_2_Lay1_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,6],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,7],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,8],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,10],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,11],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,12],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay1_history_reshape[:,13],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,14],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,15],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,16],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,17],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,18],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,19],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,20],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,21],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,22],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,23],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,24],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,25],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,26],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,27],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,28],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay1_history_reshape[:,29],linewidth=1.0,color = 'C0')
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Critic_2_Lay1_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Critic_2_Lay1_history')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

fig7= plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Critic_2_Lay2_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay2_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay2_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay2_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay2_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay2_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Critic_2_Lay2_history_reshape[:,6],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay2_history_reshape[:,7],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay2_history_reshape[:,8],linewidth=1.0,color = 'C0')
#plt.plot(Critic_2_Lay2_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Critic_2_Lay2_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Critic_2_Lay1_Weights')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

fig8= plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Actor_1_Lay1_history_reshape[:,0],linewidth=1.0,color = 'C0',label = r'$\alpha$')
plt.plot(Actor_1_Lay1_history_reshape[:,1],linewidth=1.0,color = 'C1',label = r'$e_{\alpha}$')
plt.plot(Actor_1_Lay1_history_reshape[:,2],linewidth=1.0,color = 'C2',label = r'\delta_{e}')
plt.plot(Actor_1_Lay1_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape[:,4],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape[:,5],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape[:,7],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape[:,8],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape[:,10],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape[:,11],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape[:,13],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape[:,14],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape[:,16],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape[:,17],linewidth=1.0,color = 'C2')
plt.plot(Actor_1_Lay1_history_reshape[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay1_history_reshape[:,19],linewidth=1.0,color = 'C1')
plt.plot(Actor_1_Lay1_history_reshape[:,20],linewidth=1.0,color = 'C2')
#plt.plot(Actor_1_Lay1_history_reshape[:,21],linewidth=1.0,color = 'C0')
#plt.plot(Actor_1_Lay1_history_reshape[:,22],linewidth=1.0,color = 'C1')
#plt.plot(Actor_1_Lay1_history_reshape[:,23],linewidth=1.0,color = 'C2')
#plt.plot(Actor_1_Lay1_history_reshape[:,24],linewidth=1.0,color = 'C0')
#plt.plot(Actor_1_Lay1_history_reshape[:,25],linewidth=1.0,color = 'C1')
#plt.plot(Actor_1_Lay1_history_reshape[:,26],linewidth=1.0,color = 'C2')
#plt.plot(Actor_1_Lay1_history_reshape[:,27],linewidth=1.0,color = 'C0')
#plt.plot(Actor_1_Lay1_history_reshape[:,28],linewidth=1.0,color = 'C1')
#plt.plot(Actor_1_Lay1_history_reshape[:,29],linewidth=1.0,color = 'C2')
idx = 2000
y_mark = Actor_1_Lay1_history_reshape[2000,0]
plt.scatter(idx, y_mark, s = 50)
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Actor_1_Lay1_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Actor_1_Lay1_history')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

fig20= plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Actor_1_Lay1_history_reshape[:,0],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,1],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,2],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,3],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,4],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,5],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,6],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,7],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,8],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,9],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,10],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,11],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,12],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,13],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,14],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,15],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,16],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,17],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,18],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,19],linewidth=2.0)
plt.plot(Actor_1_Lay1_history_reshape[:,20],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,21],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,22],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,23],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,24],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,25],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,26],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,27],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,28],linewidth=2.0)
#plt.plot(Actor_1_Lay1_history_reshape[:,29],linewidth=2.0)
idx = 2000
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,0], s = 50, marker = 'o', label = r'$\alpha$')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,1], s = 50, marker = '^', label = r'$e_{\alpha}$')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,2], s = 50, marker = 'D', label = r'$\delta_{e}$')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,3], s = 50, marker = 'o')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,4], s = 50, marker = '^')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,5], s = 50)
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,6], s = 50, marker = 'o')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,7], s = 50, marker = '^')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,8], s = 50)
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,9], s = 50, marker = 'o')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,10], s = 50, marker = '^')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,11], s = 50)
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,12], s = 50, marker = 'o')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,13], s = 50, marker = '^')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,14], s = 50)
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,15], s = 50, marker = 'o')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,16], s = 50, marker = '^')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,17], s = 50)
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,18], s = 50, marker = 'o')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,19], s = 50, marker = '^')
plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,20], s = 50)
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,21], s = 50, marker = 'o')
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,22], s = 50, marker = '^')
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,23], s = 50)
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,24], s = 50, marker = 'o')
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,25], s = 50, marker = '^')
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,26], s = 50)
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,27], s = 50, marker = 'o')
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,28], s = 50, marker = '^')
#plt.scatter(idx, Actor_1_Lay1_history_reshape[idx,29], s = 50)
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Actor_1_Lay1_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Actor_1_Lay1_history')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

fig9 = plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Actor_1_Lay2_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_1_Lay2_history_reshape[:,6],linewidth=1.0,color = 'C0')
#plt.plot(Actor_1_Lay2_history_reshape[:,7],linewidth=1.0,color = 'C0')
#plt.plot(Actor_1_Lay2_history_reshape[:,8],linewidth=1.0,color = 'C0')
#plt.plot(Actor_1_Lay2_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Actor_1_Lay2_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Actor_1_Lay2_history')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

fig10= plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Actor_2_Lay1_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,6],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,7],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,8],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,10],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,11],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,12],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,13],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,14],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,15],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,16],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,17],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,18],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,19],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay1_history_reshape[:,20],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,21],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,22],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,23],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,24],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,25],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,26],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,27],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,28],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay1_history_reshape[:,29],linewidth=1.0,color = 'C0')
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Actor_2_Lay1_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Actor_2_Lay1_history')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)


fig11= plt.figure(figsize=(18.0,9.0))
matplotlib.rcParams['pdf.fonttype'] = 42
matplotlib.rcParams['ps.fonttype']  = 42
plt.plot(Actor_2_Lay2_history_reshape[:,0],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape[:,1],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape[:,2],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape[:,3],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape[:,4],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape[:,5],linewidth=1.0,color = 'C0')
plt.plot(Actor_2_Lay2_history_reshape[:,6],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay2_history_reshape[:,7],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay2_history_reshape[:,8],linewidth=1.0,color = 'C0')
#plt.plot(Actor_2_Lay2_history_reshape[:,9],linewidth=1.0,color = 'C0')
plt.xlabel('Time [s]',fontdict={'size':35})
plt.ylabel('Actor_2_Lay2_history',fontdict={'size':35})
plt.xticks(fontsize=35)
plt.yticks(fontsize=35)
plt.title('Actor_2_Lay2_history')
plt.grid(True)
plt.legend(loc='upper right',bbox_to_anchor=(1,1.025),fontsize=35)

plt.show()